apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hro-dev-front-build-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: hro-dev-front-build
  podTemplate:
    imagePullSecrets:
      - name: hero-reg
  params:
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/devops-infra/web-sample.git"
  - name: git-revision
    value: "dev"
  - name: insecure-registry
    value: "false"
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/hero"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-web-sample-deploy.git"
  - name: gitops-revision
    value: "master"
  - name: deploy-manifest
    value: "kustomization.yaml"
  - name: build-stage
    value: "dev"
  - name: sonar-project-key
    value: "web-sample"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-hero-dev-build
  - name: gitops
    emptyDir: {}
  - name: manifest-dir
    emptyDir: {}

