apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hro-dev-back-build-f
spec:
  params:
    - name: build-stage
    - name: git-url
    - name: git-revision
    - name: image-url
    - name: insecure-registry
    - name: gitops-url
    - name: gitops-revision
    - name: deploy-manifest
    - name: sonar-project-key
  workspaces:
    - name: source 
    - name: gitops 
    - name: manifest-dir
  tasks:
    - name: generate-id
      taskRef:
        name: generate-build-id
      params:
        - name: base-version
          value: $(params.build-stage)
    - name: clone-sources
      taskRef:
        name: git-clone
      runAfter:
        - generate-id
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    - name: source-scan
      taskRef:
        name: sonarqube-scan
      runAfter:
        - clone-sources
      params:
        - name: SONAR_PROJECT_KEY
          value: $(params.sonar-project-key)
      workspaces:
        - name: source
          workspace: source
    - name: build-image
      taskRef:
        name: jib-maven
      runAfter:
        - source-scan
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: insecure-registry
          value: $(params.insecure-registry)
      workspaces:
        - name: source
          workspace: source
    - name: image-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
    - name: update-image
      taskRef:
        name: update
      runAfter:
        - build-image
      params:
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: build-stage
          value: $(params.build-stage)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      workspaces:
        - name: gitops
          workspace: gitops
  finally:
    - name: report-result
      taskRef:
        #name: print-result
        name: mmctl-send-result
      params:
        - name: MESSAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id) -->  $(tasks.source-scan.results.sonar-scan-result)
