apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hro-dev-back-all-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: hro-dev-back-all
  podTemplate:
    imagePullSecrets:
      - name: hero-reg
  params:
  - name: git-url
    #value: "git@gitlab.herosonsa.co.kr:devops-infra/maven-sample.git"
    value: "https://gitlab.herosonsa.co.kr/devops-infra/maven-sample.git"
  - name: git-revision
    value: "dev"
  - name: insecure-registry
    value: "false"
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/maven-sample"
  - name: argo-app-name
    value: "dev-maven-sample"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-maven-sample-deploy.git"
  - name: gitops-revision
    value: "dev"
  - name: rollout-strategy
    value: "bluegreen"
  - name: deploy-manifest
    value: "kustomization.yaml"
  - name: argo-url
    value: "argocd.herosonsa.co.kr"
  - name: build-stage
    value: "dev"
  - name: sonar-project-key
    value: "dev-maven-sample"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-hero-dev-build
  - name: gitops
    emptyDir: {}
  - name: manifest-dir
    emptyDir: {}



