global:
  imageRegistry: "tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops"
  imagePullSecrets: 
    - hero-reg
service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak.herosonsa.co.kr
